USE [master]
GO
/****** Object:  Database [Cinema]    Script Date: 09/20/2017 19:54:36 ******/
CREATE DATABASE [Cinema] ON  PRIMARY 
( NAME = N'Cinema', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Cinema.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Cinema_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Cinema_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Cinema] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cinema].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Cinema] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Cinema] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Cinema] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Cinema] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Cinema] SET ARITHABORT OFF
GO
ALTER DATABASE [Cinema] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Cinema] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Cinema] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Cinema] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Cinema] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Cinema] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Cinema] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Cinema] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Cinema] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Cinema] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Cinema] SET  DISABLE_BROKER
GO
ALTER DATABASE [Cinema] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Cinema] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Cinema] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Cinema] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Cinema] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Cinema] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Cinema] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Cinema] SET  READ_WRITE
GO
ALTER DATABASE [Cinema] SET RECOVERY FULL
GO
ALTER DATABASE [Cinema] SET  MULTI_USER
GO
ALTER DATABASE [Cinema] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Cinema] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'Cinema', N'ON'
GO
USE [Cinema]
GO
/****** Object:  Table [dbo].[Order]    Script Date: 09/20/2017 19:54:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[OrderId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_ORDER] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Halls]    Script Date: 09/20/2017 19:54:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Halls](
	[HallId] [int] NOT NULL,
	[HallName] [varchar](40) NOT NULL,
 CONSTRAINT [PK_HALLS] PRIMARY KEY CLUSTERED 
(
	[HallId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Users]    Script Date: 09/20/2017 19:54:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] NOT NULL,
	[UserName] [varchar](40) NOT NULL,
	[Role] [varchar](20) NOT NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Shows]    Script Date: 09/20/2017 19:54:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Shows](
	[ShowId] [int] NOT NULL,
	[ShowName] [varchar](40) NOT NULL,
	[Date] [datetime] NOT NULL,
	[HallId] [int] NOT NULL,
 CONSTRAINT [PK_SHOWS] PRIMARY KEY CLUSTERED 
(
	[ShowId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Rows]    Script Date: 09/20/2017 19:54:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rows](
	[RowId] [int] NOT NULL,
	[RowNumber] [int] NOT NULL,
	[HallId] [int] NOT NULL,
 CONSTRAINT [PK_ROWS] PRIMARY KEY CLUSTERED 
(
	[RowId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sold _or_Reserved_Tickets]    Script Date: 09/20/2017 19:54:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Sold _or_Reserved_Tickets](
	[TicketId] [int] NOT NULL,
	[ShowId] [int] NOT NULL,
	[PlaceNumber] [int] NOT NULL,
	[Price] [money] NOT NULL,
	[Status] [varchar](10) NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_SOLD OR RESERVED TICKETS] PRIMARY KEY CLUSTERED 
(
	[TicketId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Cross]    Script Date: 09/20/2017 19:54:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cross](
	[OrderId] [int] NOT NULL,
	[TicketId] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  ForeignKey [Shows_fk0]    Script Date: 09/20/2017 19:54:37 ******/
ALTER TABLE [dbo].[Shows]  WITH CHECK ADD  CONSTRAINT [Shows_fk0] FOREIGN KEY([HallId])
REFERENCES [dbo].[Halls] ([HallId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Shows] CHECK CONSTRAINT [Shows_fk0]
GO
/****** Object:  ForeignKey [FK_Rows_Halls]    Script Date: 09/20/2017 19:54:37 ******/
ALTER TABLE [dbo].[Rows]  WITH CHECK ADD  CONSTRAINT [FK_Rows_Halls] FOREIGN KEY([HallId])
REFERENCES [dbo].[Halls] ([HallId])
GO
ALTER TABLE [dbo].[Rows] CHECK CONSTRAINT [FK_Rows_Halls]
GO
/****** Object:  ForeignKey [Sold or Reserved Tickets_fk0]    Script Date: 09/20/2017 19:54:37 ******/
ALTER TABLE [dbo].[Sold _or_Reserved_Tickets]  WITH CHECK ADD  CONSTRAINT [Sold or Reserved Tickets_fk0] FOREIGN KEY([ShowId])
REFERENCES [dbo].[Shows] ([ShowId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Sold _or_Reserved_Tickets] CHECK CONSTRAINT [Sold or Reserved Tickets_fk0]
GO
/****** Object:  ForeignKey [Sold or Reserved Tickets_fk2]    Script Date: 09/20/2017 19:54:37 ******/
ALTER TABLE [dbo].[Sold _or_Reserved_Tickets]  WITH CHECK ADD  CONSTRAINT [Sold or Reserved Tickets_fk2] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Sold _or_Reserved_Tickets] CHECK CONSTRAINT [Sold or Reserved Tickets_fk2]
GO
/****** Object:  ForeignKey [Cross_fk0]    Script Date: 09/20/2017 19:54:37 ******/
ALTER TABLE [dbo].[Cross]  WITH CHECK ADD  CONSTRAINT [Cross_fk0] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Order] ([OrderId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Cross] CHECK CONSTRAINT [Cross_fk0]
GO
/****** Object:  ForeignKey [Cross_fk1]    Script Date: 09/20/2017 19:54:37 ******/
ALTER TABLE [dbo].[Cross]  WITH CHECK ADD  CONSTRAINT [Cross_fk1] FOREIGN KEY([TicketId])
REFERENCES [dbo].[Sold _or_Reserved_Tickets] ([TicketId])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Cross] CHECK CONSTRAINT [Cross_fk1]
GO
